export default {
    IMG_HOST: process.env.VUE_APP_PIC_BASE,
    adminRegister: '/admin/register',
    adminLogin: '/admin/login',
    adminLogout: '/admin/logout',
    adminInfo: '/admin/user_info',
    adminUpdateAvatar: '/admin/update_avatar',
    saveUser: '/user/save',
    listUser: '/user/list',
    userLabelList: '/user/label_list',
    userLabelSave: '/user/label_save',
    upload: '/upload',
    shopCategoryList: '/shop/category_list',
    shopCategorySave: '/shop/category_save',
    shopList: '/shop/list',
    shopSave: '/shop/save',
    shopDetail: '/shop/detail',
    addressChildren: '/address/query_children',
}
